import './style.css';
import { FIELDS, STATUS, PROGRESS, NUMERIC } from './fields.js';
import { newProperty,title,unresolved,confirmed,drafted,needsReview,ready,pending,touch,editField,validateUrl } from './model.js';
import * as db from './storage.js';
import { parsePages } from './parser.js';
import { loadPDF,renderPage,extractPDF } from './pdf.js';
import { generatePrompt } from './prompt.js';
import { parseResults } from './results.js';
import { exportBackup,validateBackup,validateProperty,download } from './backup.js';

const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let properties=[],settings={id:'portal',suumo:'',athome:''},selected=new Set(),filter='全件',search='',view='dashboard',current=null,pdf=null,page=1,zoom=1.3,renderQueue=Promise.resolve(),saving=Promise.resolve(),saveFailure=null,processing=false,controller=null;
const app=$('#app'),modal=$('#modal');
function notify(message,error=false) {const el=$('#notice');el.textContent=message;el.className=error?'show error':'show';if(modal.open){let note=$('.dialog-notice',modal);if(!note){note=document.createElement('p');note.className='dialog-notice';note.setAttribute('role','status');modal.append(note);}note.textContent=message;}clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.className='',error?12000:5000);}
function error(e) {console.error(e);notify(db.storageError(e),true);}
function showModal(html) {modal.innerHTML=html;modal.showModal();$('[data-close]',modal)?.addEventListener('click',()=>modal.close());}
function header() {
  return `<aside class="sidebar"><a class="brand" href="#"><span class="brand-mark">L<span>↗</span></span><div>LINE不動産<small>PROPERTY OPERATIONS</small></div></a><div class="workspace-label">WORKSPACE <span>VER. 1.0</span></div><nav><button data-view="dashboard" class="${view==='dashboard'?'active':''}"><span>▦</span> 案件ダッシュボード</button><button data-view="settings" class="${view==='settings'?'active':''}"><span>⚙</span> 設定・バックアップ</button></nav><div class="sidebar-bottom"><span class="online-dot"></span> LOCAL WORKSPACE<p>物件データはこのブラウザに保存<br>外部AI APIは使用しません</p></div></aside><div class="main"><header class="topbar"><span>PORTAL ENTRY STUDIO <em> / ${view==='editor'?'REVIEW':view==='settings'?'SETTINGS':'OVERVIEW'}</em></span><span class="version">Property Data Reader & Portal Workflow Manager</span></header><div class="safety"><b>▣ PUBLICATION LOCKED</b><span>AIによる公開操作は禁止。最終公開は人間が行います。</span><span class="safety-note">常時有効</span></div><main id="content"></main></div>`;
}
function shell() { app.innerHTML=header();$$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();navigate('dashboard');}; }
async function navigate(next) {await saving;if(saveFailure){notify('変更が未保存です。確認画面の「保存を再試行」を押してください。',true);return;}if(processing)return; if(pdf){await pdf.destroy();pdf=null;}view=next;current=null;shell();if(next==='settings')renderSettings();else renderDashboard();}
function stats() {
  const list=properties.filter(p=>!p.archived);
  return [['総案件数',list.length],['未処理',list.filter(pending).length],['Work処理待ち',list.filter(p=>confirmed(p)>0&&pending(p)&&!unresolved(p)).length],['要確認',list.filter(needsReview).length],['画像登録待ち',list.filter(p=>p.progress.photo!=='完了'||p.progress.floorplan!=='完了').length],['公開準備完了',list.filter(p=>ready(p)&&p.progress.publication!=='公開済み').length],['公開済み',list.filter(p=>p.progress.publication==='公開済み').length]];
}
function visibleProperties() {return properties.filter(p=>filter==='アーカイブ'?p.archived:!p.archived).filter(p=>({全件:true,未処理:pending(p),要確認:needsReview(p),下書き完了:drafted(p),公開準備完了:ready(p)&&p.progress.publication!=='公開済み',公開済み:p.progress.publication==='公開済み',アーカイブ:true})[filter]).filter(p=>`${title(p)} ${p.fields.unit.value} ${p.fields.address.value}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
function renderDashboard() {
  $('#content').innerHTML=`<section class="page-heading"><div><div class="eyebrow">YOUR PROPERTY WORKSPACE</div><h1>案件ダッシュボード<span class="heading-dot">.</span></h1><p>販売図面の読み取りから、入稿準備までをひとつの場所で。</p></div><button class="primary" id="add-pdf">＋ 販売図面を登録</button></section><section class="stats">${stats().map(([label,n],i)=>`<div class="stat ${i===3?'amber':''}"><span>${label}</span><strong>${String(n).padStart(2,'0')}</strong><small>${i===0?'PROPERTIES':i===6?'RECORDED':'PROGRESS'}</small></div>`).join('')}</section><section class="dropzone" id="dropzone" tabindex="0" role="button" aria-label="PDFを登録"><div class="upload-icon">↥</div><div><strong>販売図面PDFをドラッグ＆ドロップ</strong><p>またはクリックして選択 · 複数PDFに対応 · 1ファイル50MBまで</p></div><span class="local-tag">◎ ブラウザ内で解析</span></section><input type="file" id="pdf-files" accept=".pdf,application/pdf" multiple hidden><section id="processing" class="processing" hidden><div><strong id="process-label">PDF解析中</strong><button id="cancel-process">中止</button></div><progress></progress><ul id="process-log"></ul></section><section class="list-section"><div class="section-heading"><div><span class="eyebrow">PROPERTY LIBRARY</span><h2>案件一覧 <span>${properties.filter(p=>!p.archived).length}</span></h2></div><div class="actions"><button id="manual">＋ 手動登録</button><button id="results">Work結果を取込</button></div></div><div class="list-tools"><div class="filters">${['全件','未処理','要確認','下書き完了','公開準備完了','公開済み','アーカイブ'].map(f=>`<button data-filter="${f}" class="${filter===f?'chosen':''}">${f}</button>`).join('')}</div><input id="search" type="search" placeholder="物件名・号棟・所在地で検索" aria-label="案件検索" value="${esc(search)}"></div><div id="property-list"></div><div class="batchbar"><label><input type="checkbox" id="select-all"> 表示中を選択</label><span id="selected-count"></span><div class="batch-actions"><select id="mode" aria-label="Workモード"><option value="TEST">TEST MODE · 1案件</option><option value="BATCH">BATCH MODE · 複数案件</option></select><button class="primary" id="generate">Work用指示を生成 ↗</button></div></div></section><footer>LOCAL FIRST. HUMAN VERIFIED.<span>最終公開・画像登録は人間が担当します。</span></footer>`;
  renderList();$('#search').oninput=e=>{search=e.target.value;renderList();};$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderDashboard();});
  const picker=$('#pdf-files');$('#add-pdf').onclick=()=>picker.click();picker.onchange=()=>importPDFs([...picker.files]);
  const drop=$('#dropzone');drop.onclick=()=>picker.click();drop.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();picker.click();}};drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');importPDFs([...e.dataTransfer.files]);};
  $('#manual').onclick=async()=>{try{const p=newProperty();await db.saveProperty(p);properties.push(p);await openEditor(p.id);}catch(e){error(e);}};
  $('#select-all').onchange=e=>{visibleProperties().forEach(p=>e.target.checked?selected.add(p.id):selected.delete(p.id));renderList();};
  $('#generate').onclick=preparePrompt;$('#results').onclick=resultsDialog;
}
function renderList() {
  const list=visibleProperties();
  $('#property-list').innerHTML=list.length?`<div class="table-scroll"><table><thead><tr><th class="check-col"></th><th>物件 / 所在地</th><th>確認状況</th><th>SUUMO</th><th>at home</th><th>画像 / 最終確認</th><th>公開記録</th><th>更新日時</th></tr></thead><tbody>${list.map(p=>`<tr><td><input type="checkbox" data-select="${esc(p.id)}" aria-label="${esc(title(p))}を選択" ${selected.has(p.id)?'checked':''}></td><td><button class="property-link" data-open="${esc(p.id)}">${esc(title(p))} ${esc(p.fields.unit.value)}</button><small class="address">${esc(p.fields.address.value||'所在地 未入力')}</small></td><td><span class="badge ${needsReview(p)?'warning':'green'}">${needsReview(p)?'⚠ 要確認':'確認待ち / 済'}</span><small class="address">確定 ${confirmed(p)} / ${FIELDS.length}</small></td><td>${portalBadge(p.progress.suumo)}</td><td>${portalBadge(p.progress.athome)}</td><td><small class="checklist">写真 ${p.progress.photo==='完了'?'✓':'○'}　間取り ${p.progress.floorplan==='完了'?'✓':'○'}<br>最終確認 ${p.progress.final}</small></td><td><span class="badge ${p.progress.publication==='公開済み'?'green':''}">${p.progress.publication}</span></td><td class="date">${new Date(p.updatedAt).toLocaleString('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}<br><button class="text-btn" data-open="${esc(p.id)}">確認・編集 →</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><div>▤</div><h3>${search||filter!=='全件'?'該当する案件はありません':'最初の販売図面を登録しましょう'}</h3><p>PDFを登録すると、項目候補を抽出します。原本と照合してから確定してください。</p><div class="empty-flow"><span>01　PDF読取</span><i>→</i><span>02　人間が確認</span><i>→</i><span>03　Workへ引継ぎ</span></div></div>`;
  $$('[data-open]').forEach(b=>b.onclick=()=>openEditor(b.dataset.open));$$('[data-select]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.select):selected.delete(c.dataset.select);updateSelection();});updateSelection();
}
function updateSelection(){ $('#selected-count').textContent=`${selected.size} 件を選択`;const list=visibleProperties();$('#select-all').checked=!!list.length&&list.every(p=>selected.has(p.id)); }
function portalBadge(state){return `<span class="badge ${state==='下書き完了'?'green':state==='要確認'?'warning':''}">${state==='下書き完了'?'●':'○'} ${state}</span>`;}
async function importPDFs(files) {
  if(processing||!files.length)return;processing=true;controller=new AbortController();$('#processing').hidden=false;
  $$('button,input,select',app).forEach(el=>el.disabled=true);$('#cancel-process').disabled=false;$('#cancel-process').onclick=()=>controller.abort();
  const log=[];
  try {
    for(const file of files) {
      if(controller.signal.aborted) break;
      try {
        if(!/\.pdf$/i.test(file.name)||file.size>50*1024*1024||!(await file.slice(0,5).text()).startsWith('%PDF-')) throw new Error('有効なPDF（50MB以下）を選択してください。');
        const result=await extractPDF(file,msg=>$('#process-label').textContent=`${file.name} · ${msg}`,controller.signal);
        const p=parsePages(newProperty(file.name),result.pages);p.errors=result.errors;await db.saveProperty(p,file);properties.push(p);log.push(`${file.name}: 保存完了${p.errors.length?'（読取エラーあり・手動確認が必要）':''}`);
      }catch(e){if(e.name==='AbortError'){log.push('処理を中止しました。保存済みの案件は保持されています。');break;}log.push(`${file.name}: ${db.storageError(e)}`);}
      $('#process-log').innerHTML=log.map(t=>`<li>${esc(t)}</li>`).join('');
    }
  }finally{processing=false;$$('[data-view]').forEach(el=>el.disabled=false);renderDashboard();showModal(`<h2>PDF登録の結果</h2><ul class="import-log">${log.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><button data-close class="primary">閉じる</button>`);}
}
async function openEditor(id) {
  await saving;if(saveFailure){notify('変更が未保存です。保存を再試行してください。',true);return;}if(processing)return;
  current=properties.find(p=>p.id===id);if(!current)return;view='editor';page=1;zoom=1.3;shell();renderEditor();
  try {const blob=await db.getPDF(id);if(blob){const loaded=await loadPDF(blob);if(current?.id!==id){await loaded.destroy();return;}pdf=loaded;const first=await pdf.getPage(1);zoom=Math.min(1.3,($('.pdf-scroll').clientWidth-30)/first.getViewport({scale:1}).width);await paintPDF();}else if($('#pdf-message'))$('#pdf-message').textContent='原本PDFがありません。手動案件またはPDFを含まないバックアップです。';}catch(e){if($('#pdf-message'))$('#pdf-message').textContent=`PDF表示失敗: ${e.message}。手動で確認してください。`;}
}
function persist(reason) {
  touch(current,reason);const snapshot=structuredClone(current);$('#save-state').textContent='保存中…';
  saving=saving.then(()=>db.saveProperty(snapshot)).then(()=>{saveFailure=null;if($('#save-state'))$('#save-state').textContent='✓ ブラウザに保存済み';}).catch(e=>{saveFailure=e;if($('#save-state'))$('#save-state').textContent='未保存 — 保存を再試行してください';error(e);});return saving;
}
function renderEditor() {
  const p=current;
  $('#content').innerHTML=`<div class="editor-heading"><div><button class="text-btn" id="back">← 案件一覧</button><h1>${esc(title(p))}</h1><p>原本と照合し、項目ごとに確定してください。</p></div><div class="actions"><span id="save-state">✓ ブラウザに保存済み</span><button id="retry-save">保存を再試行</button><button id="archive">${p.archived?'アーカイブ解除':'アーカイブ'}</button><button class="danger" id="delete">案件削除</button></div></div><section class="review-layout"><div class="pdf-panel"><div class="panel-title"><span>販売図面 <small>ORIGINAL DOCUMENT</small></span><span class="badge">LOCAL</span></div><div class="pdf-toolbar"><button id="prev-page" aria-label="前のページ">←</button><span id="page-info">—</span><button id="next-page" aria-label="次のページ">→</button><div></div><button id="zoom-out" aria-label="縮小">−</button><span id="zoom-info">130%</span><button id="zoom-in" aria-label="拡大">＋</button></div><div class="pdf-scroll"><p id="pdf-message">PDF読込中…</p><canvas id="pdf-canvas" aria-label="販売図面の原本"></canvas></div><details class="raw-text"><summary>抽出された原文を表示</summary>${p.pages.map(pg=>`<h4>${pg.number}ページ · ${pg.method}</h4><pre>${esc(pg.text)}</pre>`).join('')||'<p>抽出テキストはありません。</p>'}</details></div><div class="fields-panel"><div class="panel-title"><span>抽出情報の確認 <small>HUMAN VERIFICATION</small></span><span id="review-count" class="badge warning"></span></div><div class="review-help">数字・単位・号棟を原本で照合してください。異なる候補は自動で選択しません。</div>${p.errors.length?`<div class="inline-warning"><strong>読取時の要確認事項</strong><ul>${p.errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><button id="resolve-errors">原本と全ページを照合し、読取エラーを解決済みにする</button></div>`:''}<div class="field-filter"><select id="field-filter" aria-label="確認項目の絞り込み"><option value="all">すべての項目</option><option value="pending">未確認・要確認</option><option value="confirmed">確定済み</option><option value="unknown">不明</option></select></div><div id="field-list"></div></div></section><section class="progress-panel"><div class="section-heading"><div><span class="eyebrow">HUMAN WORKFLOW</span><h2>入稿の進捗・管理記録</h2></div><button id="editor-results">この案件のWork結果を取込</button></div><p>「公開済み」は、人間が外部ポータルで公開した後の記録です。ここから公開操作は行いません。</p><div class="progress-grid">${Object.entries(PROGRESS).map(([key,[label,states]])=>`<label>${label}<select data-progress="${key}">${states.map(s=>`<option ${p.progress[key]===s?'selected':''}>${s}</option>`).join('')}</select></label>`).join('')}</div><label class="notes-label">人間への要確認事項・Work報告<textarea id="work-notes" rows="3" placeholder="未解決の要確認事項を残してください。解決後に消すと準備完了判定に反映されます。">${esc(p.workNotes)}</textarea></label><details><summary>変更履歴（直近100件）</summary><pre>${esc(p.history.map(h=>`${h.at} ${h.action}`).join('\n'))}</pre></details></section>`;
  renderFields();$('#back').onclick=()=>navigate('dashboard');$('#retry-save').onclick=()=>persist();
  $('#prev-page').onclick=()=>{if(pdf&&page>1){page--;paintPDF();}};$('#next-page').onclick=()=>{if(pdf&&page<pdf.numPages){page++;paintPDF();}};$('#zoom-out').onclick=()=>{zoom=Math.max(.5,zoom-.2);paintPDF();};$('#zoom-in').onclick=()=>{zoom=Math.min(3,zoom+.2);paintPDF();};
  $('#field-filter').onchange=renderFields;
  $('#archive').onclick=async()=>{p.archived=!p.archived;await persist(p.archived?'アーカイブ':'アーカイブ解除');if(!saveFailure)navigate('dashboard');};
  $('#delete').onclick=()=>showDelete(p);
  $('#resolve-errors')?.addEventListener('click',async()=>{if(!confirm('すべての読取エラーについて原本と照合し、必要な値を手動入力しましたか？'))return;p.errors=[];await persist('人間が読取エラーを解決');renderEditor();paintPDF();});
  $$('[data-progress]').forEach(el=>el.onchange=async()=>{
    const key=el.dataset.progress;
    if(key==='publication'&&el.value==='公開済み'&&!confirm('人間が外部ポータルサイトで公開した事実を記録します。公開操作は行いません。記録しますか？')){el.value=p.progress[key];return;}
    p.progress[key]=el.value;if(['suumo','athome','photo','floorplan'].includes(key)){p.progress.final='未確認';$('[data-progress="final"]').value='未確認';}await persist(`${PROGRESS[key][0]}: ${el.value}`);
  });
  $('#work-notes').oninput=e=>{p.workNotes=e.target.value;p.progress.final='未確認';$('[data-progress="final"]').value='未確認';persist();};$('#editor-results').onclick=()=>resultsDialog(p.id);
}
function renderFields() {
  const type=$('#field-filter').value;
  const fields=FIELDS.filter(f=>type==='all'||(type==='pending'?['review','unreviewed'].includes(current.fields[f.id].status):current.fields[f.id].status===type));
  let group='';$('#field-list').innerHTML=fields.map(f=>{const value=current.fields[f.id],head=group!==f.group?`<h3 class="field-group">${esc(f.group)}</h3>`:'';group=f.group;return `${head}<article class="field-card ${value.status}" data-field="${f.id}"><div class="field-label"><label for="field-${f.id}">${f.label}${NUMERIC.has(f.id)?'<small>重点確認</small>':''}</label><span class="field-state">${STATUS[value.status]}</span></div><textarea id="field-${f.id}" rows="${['transport','roads','notes','unclassified'].includes(f.id)?3:1}" placeholder="不明・資料に記載なし">${esc(value.value)}</textarea><div class="field-actions"><button data-confirm="${f.id}">✓ この値を確定</button><button data-review="${f.id}" class="text-btn">要確認にする</button><button data-unknown="${f.id}" class="text-btn">不明にする</button></div><details><summary>根拠・原文 ${value.sources.length?`(${value.sources.length})`:'（手動入力）'}</summary>${value.sources.map(s=>`<div class="source"><span>${esc(s.method)} · ${s.page}ページ</span><p>${esc(s.text)}</p></div>`).join('')}<p class="original">自動抽出値: ${esc(value.originalValue||'なし')}</p></details></article>`;}).join('')||'<p class="empty-small">該当する項目はありません。</p>';
  updateReviewCount();
  $$('[data-field] textarea').forEach(el=>el.oninput=()=>{const id=el.closest('[data-field]').dataset.field;editField(current,id,el.value);const card=el.closest('[data-field]');card.className=`field-card ${current.fields[id].status}`;$('.field-state',card).textContent=STATUS[current.fields[id].status];$('[data-progress="final"]').value=current.progress.final;updateReviewCount();persist();});
  $$('[data-confirm]').forEach(b=>b.onclick=()=>{const f=current.fields[b.dataset.confirm];if(!f.value.trim()){notify('空欄の値は確定できません。',true);return;}f.status='confirmed';f.confirmedAt=new Date().toISOString();current.progress.final='未確認';$('[data-progress="final"]').value='未確認';persist(`${b.dataset.confirm}: 原本と照合して確定`);renderFields();});
  $$('[data-review]').forEach(b=>b.onclick=()=>setFieldStatus(b.dataset.review,'review'));
  $$('[data-unknown]').forEach(b=>b.onclick=()=>setFieldStatus(b.dataset.unknown,'unknown'));
}
function setFieldStatus(id,status){current.fields[id].status=status;current.fields[id].confirmedAt=null;current.progress.final='未確認';$('[data-progress="final"]').value='未確認';persist(`${id}: ${STATUS[status]}`);renderFields();}
function updateReviewCount(){$('#review-count').textContent=`確定 ${confirmed(current)} · 未確認/要確認 ${unresolved(current)}`;}
async function paintPDF() {
  if(!pdf||!$('#pdf-canvas'))return;
  const doc=pdf,number=page,scale=zoom,canvas=$('#pdf-canvas');
  renderQueue=renderQueue.catch(()=>{}).then(async()=>{if(!canvas.isConnected||doc!==pdf)return;$('#pdf-message').textContent='';await renderPage(doc,number,canvas,scale);$('#page-info').textContent=`${number} / ${doc.numPages}`;$('#zoom-info').textContent=`${Math.round(scale*100)}%`;}).catch(error);
  return renderQueue;
}
function showDelete(p){showModal(`<h2>案件を削除しますか？</h2><p>${esc(title(p))}</p><p>原本PDFと確認済み情報も削除します。必要であれば先にバックアップを保存してください。</p><div class="dialog-actions"><button data-close>キャンセル</button><button class="danger" id="confirm-delete">この案件を削除</button></div>`);$('#confirm-delete').onclick=async()=>{try{await saving;await db.deleteProperty(p.id);saveFailure=null;properties=properties.filter(x=>x.id!==p.id);selected.delete(p.id);modal.close();await navigate('dashboard');notify('案件を削除しました。');}catch(e){error(e);}};}
function preparePrompt(){
  const targets=properties.filter(p=>selected.has(p.id)),mode=$('#mode').value;
  try {
    const output=generatePrompt(targets,mode,settings);
    const count=targets.reduce((n,p)=>n+unresolved(p),0),unknown=targets.reduce((n,p)=>n+Object.values(p.fields).filter(f=>f.status==='unknown').length,0);
    showModal(`<span class="eyebrow">WORK HANDOFF / ${mode} MODE</span><h2>確認済みデータを引き継ぐ</h2><div class="inline-warning">確認されていない項目が ${count} 件、不明項目が ${unknown} 件あります。<br>未確認・要確認・不明の値と原本PDFは出力しません。</div><p>${targets.length} 案件 · ${targets.reduce((n,p)=>n+confirmed(p),0)} 確定項目</p><div class="dialog-actions"><button data-close>確認画面へ戻る</button><button class="primary" id="confirm-generate">確認済みデータのみでWork指示を生成</button></div>`);
    $('[data-close]',modal).onclick=()=>{modal.close();if(targets.length)openEditor(targets[0].id);};
    $('#confirm-generate').onclick=()=>{showOutput(output);};
  }catch(e){notify(e.message,true);}
}
function showOutput(output){modal.innerHTML=`<span class="eyebrow">PUBLICATION LOCKED</span><h2>Work用指示</h2><p>ChatGPT Workに貼り付けてください。ログイン・画像登録・最終公開は人間が担当します。</p><textarea class="prompt-output" id="prompt-output" readonly aria-label="Work用指示">${esc(output)}</textarea><div class="dialog-actions"><button data-close>閉じる</button><button id="download-prompt">テキスト保存</button><button class="primary" id="copy-prompt">指示をコピー</button></div>`;$('[data-close]',modal).onclick=()=>modal.close();$('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText(output);notify('Work用指示をコピーしました。');}catch{$('#prompt-output').select();notify('自動コピーできません。選択されたテキストをコピーしてください。',true);}};$('#download-prompt').onclick=()=>download(new Blob([output],{type:'text/plain'}),'work-instructions.txt');}
function resultsDialog(id='') {
  showModal(`<span class="eyebrow">WORK REPORT</span><h2>Work結果を取込</h2><p>ID付きJSONを推奨します。通常テキストは対象を1案件選び、結果を確認してから反映してください。画像・最終確認・公開記録は変更しません。</p><label>テキスト報告の対象案件<select id="result-target"><option value="">ID付きJSONで自動照合</option>${properties.map(p=>`<option value="${esc(p.id)}" ${id===p.id?'selected':''}>${esc(title(p))} ${esc(p.fields.unit.value)}</option>`).join('')}</select></label><textarea id="result-input" class="result-input" aria-label="Workの最終報告" placeholder="Workの最終報告を貼り付け"></textarea><div id="result-preview"></div><div class="dialog-actions"><button data-close>閉じる</button><button class="primary" id="parse-results">解析して確認</button></div>`);
  const invalidate=()=>$('#result-preview').replaceChildren();$('#result-input').oninput=invalidate;$('#result-target').onchange=invalidate;
  $('#parse-results').onclick=()=>{try{const updates=parseResults($('#result-input').value.trim(),properties,$('#result-target').value);$('#result-preview').innerHTML=`<div class="inline-warning">案件・ポータル状態・要確認事項を確認してください。</div>${updates.map(r=>`<article class="result-card"><strong>${esc(title(properties.find(p=>p.id===r.id)))}</strong><small>${esc(r.id)}</small><p>SUUMO: ${esc(r.suumo)} / at home: ${esc(r.athome)}</p><pre>${esc(r.notes)}</pre></article>`).join('')}<button id="apply-results" class="primary">上記の解析結果を確認して反映</button>`;$('#apply-results').onclick=async()=>{try{for(const r of updates){const p=structuredClone(properties.find(p=>p.id===r.id));p.progress.suumo=r.suumo;p.progress.athome=r.athome;p.progress.final='未確認';p.workNotes=[p.workNotes,r.notes].filter(Boolean).join('\n\n');touch(p,'Work結果を人間が確認して反映');await db.saveProperty(p);properties[properties.findIndex(x=>x.id===p.id)]=p;if(current?.id===p.id)current=p;}modal.close();if(current)renderEditor();else renderDashboard();if(pdf)paintPDF();notify('Work結果を反映しました。画像登録と最終確認を行ってください。');}catch(e){error(e);}};}catch(e){notify(e.message,true);}};
}
function renderSettings() {
  $('#content').innerHTML=`<section class="page-heading"><div><span class="eyebrow">WORKSPACE SETTINGS</span><h1>設定・バックアップ<span class="heading-dot">.</span></h1><p>データを手元に。安全な運用を、いつもの流れに。</p></div></section><div class="settings-grid"><section class="settings-card"><h2>ポータル入稿ページ</h2><p>固定ページのURLのみ保存します。認証情報を入力しないでください。クエリ・フラグメント付きURLは保存できません。</p><form id="settings-form"><label>SUUMO 入稿ページURL<input id="suumo-url" type="url" placeholder="https://…" value="${esc(settings.suumo)}"></label><label>at home 入稿ページURL<input id="athome-url" type="url" placeholder="https://…" value="${esc(settings.athome)}"></label><button class="primary">URLを保存</button></form></section><section class="settings-card"><h2>データのバックアップ</h2><p>全案件・原本PDF・確認状態・進捗・設定をJSONで保存します。別のブラウザへの移行にも使用できます。</p><div class="backup-buttons"><button class="primary" id="export">↓ EXPORT BACKUP</button><button id="import">↑ IMPORT BACKUP</button></div><input id="backup-file" type="file" accept=".json,application/json" hidden><p class="muted">インポートは検証後に確認画面を表示します。同じIDは上書き、その他は保持します。</p><div id="storage-estimate" class="storage-estimate"></div><button id="persist-storage">ブラウザに永続保存を要求</button></section><section class="settings-card about"><span class="eyebrow">PRIVACY BY DESIGN</span><h2>ローカル処理と、人間による最終確認。</h2><p>販売図面および物件情報はこのブラウザ内で処理され、外部AI APIへ送信しません。PDF.js、Tesseract.jsと日本語・英語辞書を同じサイトから読み込みます。第三者CDNには接続しません。</p><p>ID・パスワード・OTP・Cookie・セッショントークンなどの認証情報は保存しません。自由入力欄やバックアップにも認証情報を含めないでください。</p><p>ブラウザのデータ削除・プライベートモード終了・端末故障でデータを失う可能性があります。バックアップは暗号化されません。適切に保管してください。同じブラウザプロファイル内の複数タブでの同時編集は避けてください。</p><div class="privacy-lock">▣ PUBLICATION LOCKED — 解除できません</div><p class="muted">LINE不動産 Portal Entry Studio Ver.1 · schemaVersion 1<br>PDFの段組み・表・縦書き・小さな文字は誤抽出の原因になります。すべて原本と照合してください。</p></section></div>`;
  $('#settings-form').onsubmit=async e=>{e.preventDefault();try{const next={id:'portal',suumo:validateUrl($('#suumo-url').value),athome:validateUrl($('#athome-url').value)};await db.saveSettings(next);settings=next;notify('入稿ページURLを保存しました。');}catch(e){notify(e.message,true);}};
  $('#export').onclick=async()=>{const button=$('#export');button.disabled=true;button.textContent='バックアップ作成中…';try{download(await exportBackup(properties,settings),`line-portal-backup-${new Date().toISOString().slice(0,10)}.json`);notify('バックアップを出力しました。');}catch(e){error(e);}finally{button.disabled=false;button.textContent='↓ EXPORT BACKUP';}};
  $('#import').onclick=()=>$('#backup-file').click();$('#backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>500*1024*1024)throw new Error('500MB以下のバックアップを指定してください。');const data=validateBackup(JSON.parse(await file.text()));const overlaps=data.properties.filter(p=>properties.some(x=>x.id===p.id)).length;showModal(`<h2>バックアップを復元</h2><p>検証済み: ${data.properties.length} 案件 / PDF ${Object.keys(data.pdfs).length} 件</p><p>同じIDの ${overlaps} 案件とURL設定を上書きします。それ以外の案件は保持します。</p><p>作成日時: ${esc(data.exportedAt)}</p><div class="dialog-actions"><button data-close>キャンセル</button><button class="primary" id="confirm-import">この内容で復元</button></div>`);$('#confirm-import').onclick=async()=>{try{await db.restoreBackup(data);properties=await db.allProperties();settings=await db.getSettings();selected.clear();modal.close();renderSettings();notify('バックアップを復元しました。');}catch(err){error(err);}};}catch(err){error(err);}};
  navigator.storage?.estimate().then(s=>{if($('#storage-estimate'))$('#storage-estimate').textContent=`使用量 約${(s.usage/1024/1024).toFixed(1)} MB / 上限 約${(s.quota/1024/1024).toFixed(0)} MB`;}).catch(()=>{});
  $('#persist-storage').onclick=async()=>{try{const ok=await navigator.storage?.persist();notify(ok?'永続保存が許可されました。定期バックアップも続けてください。':'永続保存は許可されませんでした。定期的にバックアップしてください。');}catch(e){error(e);}};
}
window.addEventListener('beforeunload',e=>{if(processing||saveFailure||$('#save-state')?.textContent==='保存中…'){e.preventDefault();e.returnValue='';}});
async function start(){shell();try{await db.openDB();const all=await db.allProperties();const corrupt=[];for(const p of all){try{validateProperty(p);properties.push(p);}catch{corrupt.push(p.id);}}settings=await db.getSettings();renderDashboard();if(corrupt.length){showModal(`<h2>読み込めない案件があります</h2><p>${corrupt.length} 件の形式が不正です。データは削除していません。</p><button id="rescue">保存データを救出JSONとして出力</button><button data-close>閉じる</button>`);$('#rescue').onclick=async()=>{try{download(await exportBackup(all,settings),'line-portal-rescue.json');}catch(e){error(e);}};}}catch(e){$('#content').innerHTML=`<div class="settings-card"><h1>保存領域を開けませんでした</h1><p>${esc(e.message)}</p><p>通常のブラウザで開き、サイトの保存許可を確認して再読み込みしてください。既存データは削除していません。</p></div>`;}}
start();
